version: '3'
services:
  database:
    image: postgis/postgis:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/postgresql/data/
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"