name: Build and Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Golang app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script:
            mkdir app &&
            cd app &&
            git clone git@github.com:kulishA/shelters-map.git &&
            echo "Deployment successful"

